# Numpy (Numerical Python)


### 1. Creating an Array in NumPy

In [1]:
# Importing numpy
import numpy as np

In [ ]:
np.array([0])

In [8]:
# Creating a simple 1 dimensional array: vector
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [5]:
# Creating 2 dimensional array: matrix
np.array([(1,2,3,4,5), (6,7,8,9,10)])

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [9]:
# Creating an array from a list

num_list = [1,2,3,4,5]
np.array(num_list)

array([1, 2, 3, 4, 5])

In [10]:
print(np.array(num_list))

[1 2 3 4 5]


### 1.1 Generating Array

NumPy offers various options to generate an array depending on particular need, such as:

* Generating identity array
* Generating zero array of a given size
* Generating ones array with a given size
* Generating an array in a given range
* Generating an array with random values


In [11]:
# Generating zero array of a given size
# 1 dimensional zero array
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [12]:
# Creating two dimensional array: pass the tuple of rows and columns' number
#np.zeros((rows, columns))

np.zeros((5,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [13]:
# Generating ones array of a given size
# 1 dimensional one array

np.ones(5)

array([1., 1., 1., 1., 1.])

In [14]:
# Creating two dimensional ones array: pass the tuple of rows and columns' number
# np.ones((rows, columns))

np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [16]:
# Any other number
np.full((2,3), 99)

array([[99, 99, 99],
       [99, 99, 99]])

In [21]:
#  Uninitialized array
np.empty((2, 2)) 

array([[6.23042070e-307, 4.67296746e-307],
       [1.69121096e-306, 1.38354126e-311]])

`np.arange(start, stop, step)` generates a sequence of spaced values within a specified range.

In [22]:
# Generating an array in a given range or interval
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [23]:
# If you want to control the step size
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

`np.linspace(start, stop, num)`

In [24]:
# You can also use linspace to generate an evenly spaced numbers in a given interval
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

In [25]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [26]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [30]:
# Generating an array with random values
# Create a 1D array with 4 random numbers
np.random.rand(4)

array([0.26199428, 0.57440749, 0.75958772, 0.0353319 ])

In [31]:
np.random.rand(4)
# We will not get the same values

array([0.53147254, 0.28836713, 0.21193398, 0.34545471])

In [32]:
np.random.rand(4,5)

array([[0.83149467, 0.87831276, 0.24772485, 0.20293583, 0.43815135],
       [0.47164545, 0.71811905, 0.85231529, 0.49368319, 0.50401772],
       [0.19996633, 0.31558525, 0.05147391, 0.12549078, 0.99255242],
       [0.44941107, 0.52678088, 0.07392973, 0.38631061, 0.04193747]])

`np.random.randint(low, high, size) `

In [33]:
# Generate one random integer in a given range
np.random.randint(5,50)

48

In [35]:
# Generate 10 random integers in a given range
np.random.randint(5,50,10)

array([34, 25, 33, 21, 32, 49, 45, 42, 27, 11], dtype=int32)

| **Feature**    | `np.identity()`          | `np.eye()`          |
|-------------|--------------------|--------------------|
| Shape  | Always square (NxN)| Square or rectangular (NxM)|
| Diagonal Shift (`k`) | Not supported| Supported (can shift diagonal)|
| Use Case | Basic identity matrices| Flexible identity and diagonal matrices|

In [47]:
# Generating an identity array
np.identity(4) # Always square (NxN)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [39]:
# Generating an identity matrix of 1s
np.eye(4) # Square

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [41]:
np.eye(3, 4) # Rectangular

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [42]:
np.eye(4, k=1) # Shifted Diagonal

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [43]:
np.eye(4) * 7

array([[7., 0., 0., 0.],
       [0., 7., 0., 0.],
       [0., 0., 7., 0.],
       [0., 0., 0., 7.]])

### 2. Data Selection: Indexing and slicing 
Indexing: Selecting individual elements from the array

Slicing: Selecting group of element from the array.


### 2.1 1D Array Indexing and Selection

In [51]:
# Creating a 1 dimensional vector
array_1d = np.array([1,2,3,4,5])

In [50]:
# Indexing: selcting an element from an array
array_1d[1]

np.int64(2)

In [52]:
# selecting last element from an array
array_1d [-1]

np.int64(5)

In [55]:
# Slicing: Returning the range of elements from an array
array_1d [2:4] # 4 excluded

array([3, 4])

### 2.2 2D Array Indexing and Selection

In [56]:
array_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [57]:
## Selecting whole second row
# array_2d[row]

array_2d[1]     # (we start from 0!!)

array([4, 5, 6])

In [58]:
## let's select the value (5) that is row 1, column 1
# array_2d[row][column]

array_2d[1][1]

np.int64(5)

In [59]:
## Let's select the first two rows

array_2d[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

**Note:** ``array_2d[:2]`` is the same as ``array_2d[0:2]``

In [60]:
## Selecting all first two rows and first two columns
array_2d[:2,0:2]

array([[1, 2],
       [4, 5]])

### 2.3 Conditional selection

In [2]:
import numpy as np

In [3]:
## Create an array
arr= np.array(([1,2,3],[4,5,6],[7,8,9]))
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
# Select all elements in an array which are less than 6

arr[arr < 6]

array([1, 2, 3, 4, 5])

In [64]:
# Select all even numbers in an array

arr[arr % 2 ==0 ]

array([2, 4, 6, 8])

### 3. Basic Array Operations

### 3.1 Quick Arithmetic operation

In [65]:
# Create two arrays
arr1 = np.arange(0,5)   # same as arr1 = [0, 1, 2, 3, 4]
arr2 = np.arange(6,11)  # same as arr2 = [6, 7, 8, 9, 10]

In [66]:
# Addition
arr1 + arr2

array([ 6,  8, 10, 12, 14])

In [67]:
# Subtraction
arr2 - arr1

array([6, 6, 6, 6, 6])

In [68]:
# Multiplication
arr1 * arr2

array([ 0,  7, 16, 27, 40])

In [69]:
# Division
arr1 / arr2

array([0.        , 0.14285714, 0.25      , 0.33333333, 0.4       ])

In [70]:
# Squaring
arr1 ** 2

array([ 0,  1,  4,  9, 16])

### 3.2 Universal functions

In [71]:
# Calculating the sum of two arrays
np.add(arr1, arr2)

array([ 6,  8, 10, 12, 14])

In [72]:
# Calculating the product of two arrays
np.multiply(arr1, arr2)

array([ 0,  7, 16, 27, 40])

In [73]:
# Calculating the difference between two arrays
np.subtract(arr1, arr2)

array([-6, -6, -6, -6, -6])

In [74]:
# Calculating the division of two arrays
np.divide(arr1, arr2)

array([0.        , 0.14285714, 0.25      , 0.33333333, 0.4       ])

In [75]:
# Calculating the sin of arr1
np.sin(arr1)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [76]:
# Calculating the cosine of arr 1
np.cos(arr1)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [78]:
# Calculating the tangent(tan) of the array
np.tan(arr2)

array([-0.29100619,  0.87144798, -6.79971146, -0.45231566,  0.64836083])

In [79]:
# Calculating the logarithmic(log) of the array
np.log(arr2)

array([1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [80]:
# Calculating the exponent(exp or e^) of the array
np.exp(arr2)

array([  403.42879349,  1096.63315843,  2980.95798704,  8103.08392758,
       22026.46579481])

In [81]:
# Calculating the power  of the array
# Array 1 is powered array 2
np.power(arr1, arr2)

array([      0,       1,     256,   19683, 1048576])

In [82]:
# Comparison operations return true or false
np.greater(arr1, arr2)

array([False, False, False, False, False])

In [83]:
## Comparison operations
np.less(arr1, arr2)

array([ True,  True,  True,  True,  True])

### 4. Basic Statistics

In [84]:
# Creating an array
arr = np.arange(0,5)
arr

array([0, 1, 2, 3, 4])

In [86]:
# calculating the standard deviation of the array
np.std(arr)

np.float64(1.4142135623730951)

In [87]:
# Calculating the Variance (var)
np.var(arr)

np.float64(2.0)

In [88]:
# Calculating the mean of the array
np.mean(arr)

np.float64(2.0)

In [89]:
# mean gives the same results as the average
np.average(arr)

np.float64(2.0)

In [90]:
# Calculating the median of the array
np.median(arr)

np.float64(2.0)

In [91]:
# Calculating the minimum value
np.min(arr)

np.int64(0)

In [92]:
# Calculating the maximum value
np.max(arr)

np.int64(4)

### 5. Data Manipulation

In [96]:
# Creating an array
arr1 = np.arange(0,10)
arr2 = np.array(([1,2,3],[4,5,6],[7,8,9]))

In [97]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [98]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [99]:
np.shape(arr1)

(10,)

In [100]:
np.shape(arr2)

(3, 3)

In [101]:
arr2.shape

(3, 3)

`np.reshape(array_name, newshape=(rows, columns)` or `array_name.reshape(rows, columns)` change the shape of the array. The rows and columns of the new shape has to comform with the existing data of the array. Otherwise, it won't work. Take an example, you can convert (3,3) array into (1,9) but you can't convert it into (5,5).

In [105]:
np.reshape(arr1, shape=(5,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [106]:
## This would also work
arr1.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [109]:
arr2_reshaped = arr2.reshape(9,1)
arr2_reshaped

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [110]:
# Transposing array changes shape from (9,1) to (1,9)
arr2_reshaped.T

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

**arr1:**
```
[[1 2 3]
 [4 5 6]
 [7 8 9]]
```
**arr2:**
```
[[10 11 12]]
```
**np.concatenate((arr1, arr2)):**
```
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
```


In [112]:
### Creating two arrays
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]]) # 3x3
arr2 = np.array([[10,11,12]]) # 1x3
# have same no of columns

In [113]:
# Joining them
np.concatenate((arr1, arr2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

**arr1:**
```
[[1 2 3]
 [4 5 6]
 [7 8 9]]
```
**arr2.T:**
```
[[10]
 [11]
 [12]]
```
**np.concatenate((arr1, arr2.T), axis=1):**
```
[[ 1  2  3 10]
 [ 4  5  6 11]
 [ 7  8  9 12]]
```


In [114]:
np.concatenate((arr1, arr2.T), axis=1)

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 11],
       [ 7,  8,  9, 12]])

**arr1:**
```
[[1 2 3]
 [4 5 6]
 [7 8 9]]
```
**arr2:**
```
[[10 11 12]]
```
**np.concatenate((arr1, arr2), axis=None):**
```
[ 1  2  3  4  5  6  7  8  9 10 11 12]
```


In [115]:
### Setting axis to none flatten the array

np.concatenate((arr1, arr2), axis=None)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [116]:
arr1 = np.arange(0,6)
arr1

array([0, 1, 2, 3, 4, 5])

In [118]:
# Splitting the array into two arrays
np.split(arr1, 2)

[array([0, 1, 2]), array([3, 4, 5])]